from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer, ChatterBotCorpusTrainer

bot = ChatBot('chatbot', read_only=False, logic_adapter=[
    {
        'import_path': 'chatterbot.logic.BestMatch',
    }
])

list_to_train = [
    "Hi", #question1
    "Hi there!", #answer1
    "Hello", 
    "Hello I am EduGuideBot",
    "What's your name?",
    "I am EduGuideBot",
    "What is your job?",
    "I am here to guide you about IOE Admission"
    "What is the full form of IOE?",
    "The full form of IOE is Institute of Engineering",
    "Where is Chitwan Engineering Campups?",
    "It lies in Bharatpur Municipality in Chitwan district.",
    "What program is taught in Chitwan?",
    "Bachelor's in Architecture",
    "What colleges are affiliated to Tribhuwan University?",
    "Kantipur Engineering College, Kathmandu Engineering College, Himalaya Engineering College, Advanced College of Engineering and Management, National College of Engineering, Kathford International College, Janakpur Engineering College, Khwopa College of Engineering, Sagarmatha College of Engineering, Lalitpur Engineering College",
    "Kantipur Engineering College affiliated to Tribhuwan University?",
    "Yes",
    "Kathmandu Engineering College affiliated to Tribhuwan University?",
    "Yes",
    "Himalaya College of Engineering affiliated to Tribhuwan University?",
    "Yes",
    "Advanced College of Engineering affiliated to Tribhuwan University?",
    "Yes",
    "National College of Engineering affiliated to Tribhuwan University?",
    "Yes",
    "Kathford International College of Engineering and Management affiliated to Tribhuwan University?",
    "Yes",
    "Janakpur Engineering College affiliated to Tribhuwan University?",
    "Yes",
    "Khowpa College of Engineering affiliated to Tribhuwan University?",
    "Yes",
    "Sagarmatha Engineering College affiliated to Tribhuwan University?",
    "Yes",
    "Lalitpur Engineering College affiliated to Tribhuwan University?",
    "Yes",
    "Do I need to pass the Entrance Examination conducted by Institute of Engineering to get admission in to the affiliated colleges?",
    "Yes",
    "What are fee programs of the affiliated colleges?",
    "10 percent of the total seats should be enrolled with regular fee.",
    "Pulchowk Campus seats for Civil Engineering?",
    "108 for regular, 84 for full fee",
    "Pulchowk Campus seats for Architecture?",
    "24 for regular, 24 for full fee",
    "Pulchowk Campus seats for Electrical Engineering?",
    "36 for regular, 60 for full fee",
    "Pulchowk Campus seats for Electronics, Communication and Information Engineering?",
    "24 for regular, 24 for full fee",
    "Pulchowk Campus seats for Mechanical Engineering?",
    "24 for regular, 24 for full fee",
    "Pulchowk Campus seats for Computer Engineering?",
    "36 for regular, 60 for full fee",
    "Pulchowk Campus seats for Aerospace Engineering?",
    "12 for regular, 36 for full fee",
    "Pulchowk Campus seats for Agriculture Engineering?",
    "0 for regular, 0 for full fee",
    "Pulchowk Campus seats for Industrial Engineering?",
    "0 for regular, 0 for full fee",
    "Pulchowk Campus seats for Geomatics Engineering?",
    "0 for regular, 0 for full fee",
    "Pulchowk Campus seats for Automobile Engineering?",
    "0 for regular, 0 for full fee",
    "Pulchowk Campus seats for Chemical Engineering?",
    "12 for regular, 36 for full fee",
    "Pashimanchal Campus WRC seats for Civil Engineering?",
    "36 for regular, 108 for full fee",
    "Pashimanchal Campus WRC seats for Architecture?",
    "0 for regular, 0 for full fee",
    "Pashimanchal Campus WRC seats for Electrical Engineering?",
    "12 for regular, 36 for full fee",
    "Pashimanchal Campus WRC seats for Electronics, Communication and Information Engineering?",
    "12 for regular, 36 for full fee",
    "Pashimanchal Campus WRC seats for Mechanical Engineering?",
    "12 for regular, 36 for full fee",
    "Pashimanchal Campus WRC seats for Computer Engineering?",
    "12 for regular, 36 for full fee",
    "Pashimanchal Campus WRC seats for Aerospace Engineering?",
    "0 for regular, 0 for full fee",
    "Pashimanchal Campus WRC seats for Agriculture Engineering?",
    "0 for regular, 0 for full fee",
    "Pashimanchal Campus WRC seats for Industrial Engineering?",
    "0 for regular, 0 for full fee",
    "Pashimanchal Campus WRC seats for Geomatics Engineering?",
    "12 for regular, 36 for full fee",
    "Pashimanchal Campus WRC seats for Automobile Engineering?",
    "12 for regular, 36 for full fee",
    "Pashimanchal Campus WRC seats for Chemical Engineering?",
    "0 for regular, 0 for full fee",
    "Purwanchal Campus ERC seats for Civil Engineering?",
    "36 for regular, 108 for full fee",
    "Purwanchal Campus ERC seats for Architecture?",
    "12 for regular, 36 for full fee",
    "Purwanchal Campus ERC seats for Electrical Engineering?",
    "12 for regular, 36 for full fee",
    "Purwanchal Campus ERC seats for Electronics, Communication and Information Engineering?",
    "12 for regular, 36 for full fee",
    "Purwanchal Campus ERC seats for Mechanical Engineering?",
    "24 for regular, 72 for full fee",
    "Purwanchal Campus ERC seats for Computer Engineering?",
    "24 for regular, 72 for full fee",
    "Purwanchal Campus ERC seats for Aerospace Engineering?",
    "0 for regular, 0 for full fee",
    "Purwanchal Campus ERC seats for Agriculture Engineering?",
    "12 for regular, 36 for full fee",
    "Purwanchal Campus ERC seats for Industrial Engineering?",
    "0 for regular, 0 for full fee",
    "Purwanchal Campus ERC seats for Geomatics Engineering?",
    "0 for regular, 0 for full fee",
    "Purwanchal Campus ERC seats for Automobile Engineering?",
    "0 for regular, 0 for full fee",
    "Purwanchal Campus ERC seats for Chemical Engineering?",
    "0 for regular, 0 for full fee",
    "Thapathali Campus seats for Civil Engineering?",
    "36 for regular, 108 for full fee",
    "Thapathali Campus seats for Architecture?",
    "12 for regular, 36 for full fee",
    "Thapathali Campus seats for Electrical Engineering?",
    "0 for regular, 0 for full fee",
    "Thapathali Campus seats for Electronics, Communication and Information Engineering?",
    "12 for regular, 36 for full fee",
    "Thapathali Campus seats for Mechanical Engineering?",
    "12 for regular, 36 for full fee",
    "Thapathali Campus seats for Computer Engineering?",
    "12 for regular, 36 for full fee",
    "Thapathali Campus seats for Aerospace Engineering?",
    "0 for regular, 0 for full fee",
    "Thapathali Campus seats for Agriculture Engineering?",
    "0 for regular, 0 for full fee",
    "Thapathali Campus seats for Industrial Engineering?",
    "12 for regular, 36 for full fee",
    "Thapathali Campus seats for Geomatics Engineering?",
    "0 for regular, 0 for full fee",
    "Thapathali Campus seats for Automobile Engineering?",
    "12 for regular, 36 for full fee",
    "Thapathali Campus seats for Chemical Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Civil Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Architecture?",
    "6 for regular, 18 for full fee",
    "Chitwan Campus seats for Electrical Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Electronics, Communication and Information Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Mechanical Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Computer Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Aerospace Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Agriculture Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Industrial Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Geomatics Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Automobile Engineering?",
    "0 for regular, 0 for full fee",
    "Chitwan Campus seats for Chemical Engineering?",
    "0 for regular, 0 for full fee",
    "Seats in Kantipur Engineering College for Civil Engineering",
    "96",
    "Seats in Kantipur Engineering College for Architecture",
    "0",
    "Seats in Kantipur Engineering College for Electrical Engineering",
    "0",
    "Seats in Kantipur Engineering College for Electronics, Communication and Information Engineering",
    "96",
    "Seats in Kantipur Engineering College for Computer Engineering",
    "96",
    "Seats in Kathmandu Engineering College for Civil Engineering",
    "96",
    "Seats in Kathmandu Engineering College for Architecture",
    "48",
    "Seats in Kathmandu Engineering College for Electrical Engineering",
    "48",
    "Seats in Kathmandu Engineering College for Electronics, Communication and Information Engineering",
    "96",
    "Seats in Kathmandu Engineering College for Computer Engineering",
    "96",
    "Seats in Himalaya Engineering College for Civil Engineering",
    "96",
    "Seats in Himalaya Engineering College for Architecture",
    "48",
    "Seats in Himalaya Engineering College for Electrical Engineering",
    "0",
    "Seats in Himalaya Engineering College for Electronics, Communication and Information Engineering",
    "48",
    "Seats in Himalaya Engineering College for Computer Engineering",
    "48",
    "Seats in Advanced College of Engineering for Civil Engineering",
    "96",
    "Seats in Advanced College of Engineering for Architecture",
    "0",
    "Seats in Advanced College of Engineering for Electrical Engineering",
    "48",
    "Seats in Advanced College of Engineering for Electronics, Communication and Information Engineering",
    "96",
    "Seats in Advanced College of Engineering for Computer Engineering",
    "96",
    "Seats in National College of Engineering for Civil Engineering",
    "96",
    "Seats in National College of Engineering for Architecture",
    "0",
    "Seats in National College of Engineering for Electrical Engineering",
    "48",
    "Seats in National College of Engineering for Electronics, Communication and Information Engineering",
    "48",
    "Seats in National College of Engineering for Computer Engineering",
    "48",
    "Seats in Kathford Internationl College of Engineering for Civil Engineering",
    "96",
    "Seats in Kathford Internationl College of Engineering for Architecture",
    "0",
    "Seats in Kathford Internationl College of Engineering for Electrical Engineering",
    "0",
    "Seats in Kathford Internationl College of Engineering for Electronics, Communication and Information Engineering",
    "48",
    "Seats in Kathford Internationl College of Engineering for Computer Engineering",
    "48",
    "Seats in Janakpur Engineering College for Civil Engineering",
    "96",
    "Seats in Janakpur Engineering College for Architecture",
    "0",
    "Seats in Janakpur Engineering College for Electrical Engineering",
    "0",
    "Seats in Janakpur Engineering College for Electronics, Communication and Information Engineering",
    "48",
    "Seats in Janakpur Engineering College for Computer Engineering",
    "48",
    "Seats in Khowpa College of Engineering for Civil Engineering",
    "96",
    "Seats in Khowpa College of Engineering for Architecture",
    "0",
    "Seats in Khowpa College of Engineering for Electrical Engineering",
    "48",
    "Seats in Khowpa College of Engineering for Electronics, Communication and Information Engineering",
    "0",
    "Seats in Khowpa College of Engineering for Computer Engineering",
    "48",
    "Seats in Sagarmatha Engineering College for Civil Engineering",
    "48",
    "Seats in Sagarmatha Engineering College for Architecture",
    "0",
    "Seats in Sagarmatha Engineering College for Electrical Engineering",
    "0",
    "Seats in Sagarmatha Engineering College for Electronics, Communication and Information Engineering",
    "48",
    "Seats in Sagarmatha Engineering College for Computer Engineering",
    "48",
    "Seats in Lalitpur Engineering College for Civil Engineering",
    "48",
    "Seats in Lalitpur Engineering College for Architecture",
    "0",
    "Seats in Lalitpur Engineering College for Electrical Engineering",
    "0",
    "Seats in Lalitpur Engineering College for Electronics, Communication and Information Engineering",
    "0",
    "Seats in Lalitpur Engineering College for Computer Engineering",
    "48",
    "What happens if the program is postponed after I've already paid the admission fee?",
    " If the program is postponed, the campus will refund your admission fee in full.",
    "Can I still apply for the program even if it's postponed?",
    "If the program is postponed, you won't be able to enroll in it for that year. However, you can consider applying for other programs or waiting to see if the program is offered in subsequent years.",
    " How will I know if the program is being postponed?",
    "The campus will communicate any decision to postpone a program through official channels, such as the website or email. You should regularly check for updates regarding the status of the program.",
    "Will I be able to get admission into another program if the one I applied for is postponed?",
    "Yes, you can explore other programs offered by the campus and apply accordingly. Your application for the postponed program won't affect your eligibility for other programs.",
    "What does it mean to transfer from the full-fee side to the regular side?",
    "Transferring from the full-fee side to the regular side means that students who initially paid the full fee to secure admission will be transferred to the regular side once the full-fee quota is filled. This allows students to switch to the regular quota without any additional cost.",
    "How will I know if I'm eligible for transfer to the regular side?",
    " Eligibility for transfer to the regular side will be based on merit order. Once the full-fee quota is filled, students will be transferred to the regular side according to their merit ranking.",
    " What happens if I've already paid the full fee but get transferred to the regular side?",
    "If you've already paid the full fee but are transferred to the regular side, you may be eligible for a refund of the difference between the full fee and the regular fee. The campus will provide guidance on the refund process.",
    "What is the difference between regular admission and full-fee admission?",
    "Regular admission entails paying the minimum tuition fees, while full-fee admission allows applicants to secure admission by paying higher fees.",
    "How are applicants admitted to the graduate (B.E./B.Arch.) level programs at the Institute of Engineering campuses?",
    "Applicants interested in studying at Pulchok Campus, Western Campus, Purvanchal Campus, Thapathali Campus, Chitwan Engineering Campus, and affiliated colleges must take the entrance exam conducted by the Institute of Engineering Studies. Admission is based on merit, determined by the entrance exam scores.",
    "What are the minimum qualifications required to apply for the entrance examination?",
    "Applicants must have obtained at least 45 percent of the total marks in the proficiency certificate level, higher secondary level, A level, or engineering diploma level examinations, with physics, chemistry, and mathematics as subjects. Alternatively, students who have obtained a minimum C Grade in each subject or have appeared in the final examination of class 12 or engineering diploma sixth-semester examination are also eligible to apply.",
    " Can students with a letter grading system apply for the entrance examination?",
    " Yes, students with a letter grading system can apply for the entrance examination if they have obtained a minimum C Grade in each subject.",
    "Are there any specific subject requirements for the entrance examination?",
    "Yes, applicants must have studied physics, chemistry, and mathematics in classes 11 and 12 or equivalent levels to be eligible for the entrance examination.",
    " Are there any exceptions to the minimum qualifications for application?",
    "Exceptions are made for students who have appeared in the final examination of class 12 or equivalent or have appeared in the sixth-semester examination of an engineering diploma program.",
    "Can applicants from educational institutions outside the country apply for the entrance examination?",
    "Yes, applicants who have completed their education from educational institutions recognized by the Vidya Parishad are eligible to apply for the entrance examination, provided they meet the minimum qualification criteria.",
    "What method will be used for conducting the entrance examination?",
    "The entrance examination will be conducted through a computer examination system based on information technology, ensuring a standardized and efficient assessment process.",
    "Who will be responsible for conducting the entrance examination?",
    "The entrance examination will be conducted by the board responsible for administering admissions to the graduate (B.E./B.Arch.) level programs.",
    " How much weightage will the entrance exam results carry in the admission process?",
    "The results of the entrance examination will carry 100 percent weightage in determining the eligibility of applicants for admission to the campus based on merit.",
    "What subjects will be covered in the entrance examination?",
    "The entrance examination will cover four subjects: Mathematics, Physics, Chemistry, and English, based on the 10+2 level syllabus.",
    "How long will the entrance examination last?",
    "The duration of the entrance examination, conducted through a fully computerized examination system, will be two hours. Additionally, there will be a penalty of deducting 10% marks for each wrong answer.",
    "What documents are required for filling the online admission form and appearing for the entrance exam?",
    "Applicants must bring a color-printed admit card and upload proof of identification documents (such as Citizenship Certificate, National Identity Card, Passport, Driver's License, or relevant academic certificates) when filling the online admission form. These documents must also be presented during the entrance examination for verification purposes.",
    "How will the entrance examination results be evaluated and presented?",
    "The entrance score will be calculated as a percentage of the total score of the entrance exam. A merit list of candidates who have obtained the minimum passing percentage or above will be published on the website entrance.ioe.edu.np.",
    " Where can I find information about admission-related procedures and activities?",
    "Information about admission-related work can be obtained from the web address of the Central Admission Committee: admission.ioe.edu.np, as well as from the websites of related campuses and colleges.",
    "How will candidates be selected for admission based on merit?",
    " Merit list for admission will be published based on the entrance score, with candidates who have obtained the minimum marks percentage or more in the entrance examination being included. In case of equality in scores, priority will be given to candidates based on certain criteria, including subject-wise scores and previous academic performance.",
    "What happens if two or more candidates have the same entrance score?",
    "In case of equality in entrance scores, priority will be determined by calculating the total result to three decimal places. If scores are still equal, preference will be given to the candidate with higher marks in Mathematics, Physics, Chemistry, and English subjects. Subsequently, preference will be given to the candidate with higher scores in their 10+2 or equivalent and SLC/SEE exams, respectively.",
    "Will the merit list be published in a specific order?",
    "Yes, the merit list will be published in a specific order based on the criteria mentioned above, ensuring transparency and fairness in the selection process.",
    "How will the admission list be published for affiliated campuses and colleges under the Institute of Engineering Studies?",
    "The admission list publication and admission process for affiliated campuses and colleges will be centralized under the Institute of Engineering Studies. The lists will be published by the Monitoring Committee and can be viewed later at admission.ioe.edu.np for reference.",
    "What is the process for admission according to the admission schedule?",
    "According to the admission schedule published by the Central Admission Monitoring Committee, respective campuses/colleges will publish the admission list in merit order based on the names published in the merit list by the Entrance Examination Board. Applicants for the architecture program may also need to take an aptitude test related to the subject.",
    " How are applicants selected for admission in reserved quotas for affiliated campuses of TU?",
    "Names of applicants who apply for admission in any reserved quota for affiliated campuses of TU will be published based on merit only during the first stage admission program (first, second, and third lists). However, applicants admitted in the reserved quota in one campus cannot be readmitted in the reserved quota in another campus.",
    "Will there be any additional tests for applicants applying for the architecture program?",
    " Yes, applicants whose names have been published for admission to the architecture program may be required to take an aptitude test (Aptitude Test) related to that subject by the respective campuses/colleges."
]

chatterbotCorpusTrainer = ChatterBotCorpusTrainer(bot)

list_trainer = ListTrainer(bot)
list_trainer.train(list_to_train)
chatterbotCorpusTrainer.train('chatterbot.corpus.english')

def index(request):
    return render(request, 'app/index.html')

def specific(request):
    return HttpResponse("number")

def getResponse(request):
    userMessage = request.GET.get('userMessage')
    chatResponse = str(bot.get_response(userMessage))
    if chatResponse == "":
        chatResponse = "I'm sorry, I don't understand. Could you please rephrase?"
    return HttpResponse(chatResponse)